-- ProDev: a focused dark theme for long professional coding sessions.

local c = {
  bg = "#1E2024",          -- Charcoal grey text editor background
  bg_alt = "#25282F",      -- Lighter grey for sidebars
  bg_float = "#2C2F37",    -- For dialogs/floats
  bg_active = "#373B45",   -- For active lists/lines
  fg = "#D7DAE0",
  fg_bright = "#EFF2F6",
  muted = "#9AA4B2",
  subtle = "#464D5A",
  border = "#333742",

  blue = "#82AAFF",
  cyan = "#4FD6E8",
  green = "#8FE388",
  yellow = "#EBCB8B",
  orange = "#F3A96A",
  red = "#EF8A8A",
  purple = "#C099FF",
}

local hl = {
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg_alt },
  NormalFloat = { fg = c.fg, bg = c.bg_float },
  FloatBorder = { fg = c.border, bg = c.bg_float },
  FloatTitle = { fg = c.blue, bg = c.bg_float },
  Cursor = { fg = c.bg, bg = c.yellow },
  lCursor = { fg = c.bg, bg = c.cyan },
  CursorIM = { fg = c.bg, bg = c.cyan },
  TermCursor = { fg = c.bg, bg = c.yellow },
  TermCursorNC = { fg = c.muted, bg = c.bg_active },
  CursorLine = { bg = c.bg_alt },
  CursorLineNr = { fg = c.yellow },
  LineNr = { fg = c.subtle },
  SignColumn = { bg = c.bg },
  ColorColumn = { bg = c.bg_alt },
  VertSplit = { fg = c.border },
  WinSeparator = { fg = c.border },
  Visual = { bg = "#384152" },
  Search = { fg = c.bg, bg = c.yellow },
  IncSearch = { fg = c.bg, bg = c.orange },
  CurSearch = { fg = c.bg, bg = c.orange },
  MatchParen = { fg = c.cyan, bg = c.bg_active },
  Pmenu = { fg = c.fg, bg = c.bg_float },
  PmenuSel = { fg = c.fg_bright, bg = "#374258" },
  PmenuSbar = { bg = c.bg_alt },
  PmenuThumb = { bg = c.subtle },
  StatusLine = { fg = c.fg, bg = c.bg_float },
  StatusLineNC = { fg = c.muted, bg = c.bg_alt },
  TabLine = { fg = c.muted, bg = c.bg_alt },
  TabLineSel = { fg = c.fg_bright, bg = c.bg },
  TabLineFill = { bg = c.bg_alt },
  Folded = { fg = c.muted, bg = c.bg_alt },
  Directory = { fg = c.blue },
  Title = { fg = c.purple },
  NonText = { fg = c.subtle },
  Whitespace = { fg = c.subtle },
  EndOfBuffer = { fg = c.bg },

  Comment = { fg = c.muted },
  Constant = { fg = c.orange },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.orange },
  Boolean = { fg = c.orange },
  Float = { fg = c.orange },
  Identifier = { fg = c.fg },
  Function = { fg = c.blue },
  Statement = { fg = c.purple },
  Conditional = { fg = c.purple },
  Repeat = { fg = c.purple },
  Label = { fg = c.purple },
  Operator = { fg = c.cyan },
  Keyword = { fg = c.purple },
  Exception = { fg = c.red },
  PreProc = { fg = c.purple },
  Include = { fg = c.purple },
  Define = { fg = c.purple },
  Macro = { fg = c.purple },
  Type = { fg = c.cyan },
  StorageClass = { fg = c.purple },
  Structure = { fg = c.cyan },
  Special = { fg = c.yellow },
  SpecialChar = { fg = c.yellow },
  Delimiter = { fg = c.fg_bright },
  Underlined = { fg = c.blue, underline = true },
  Error = { fg = c.red },
  Todo = { fg = c.yellow },

  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.purple },
  ["@variable.parameter"] = { fg = c.yellow },
  ["@variable.member"] = { fg = c.cyan },
  ["@constant"] = { fg = c.orange },
  ["@constant.builtin"] = { fg = c.orange },
  ["@module"] = { fg = c.cyan },
  ["@string"] = { fg = c.green },
  ["@string.escape"] = { fg = c.yellow },
  ["@string.special.url"] = { fg = c.blue, underline = true },
  ["@number"] = { fg = c.orange },
  ["@boolean"] = { fg = c.orange },
  ["@type"] = { fg = c.cyan },
  ["@type.builtin"] = { fg = c.cyan },
  ["@attribute"] = { fg = c.yellow },
  ["@function"] = { fg = c.blue },
  ["@function.call"] = { fg = c.blue },
  ["@function.method"] = { fg = c.blue },
  ["@function.method.call"] = { fg = c.blue },
  ["@constructor"] = { fg = c.cyan },
  ["@keyword"] = { fg = c.purple },
  ["@keyword.import"] = { fg = c.purple },
  ["@keyword.return"] = { fg = c.red },
  ["@keyword.conditional"] = { fg = c.purple },
  ["@keyword.repeat"] = { fg = c.purple },
  ["@operator"] = { fg = c.cyan },
  ["@property"] = { fg = c.cyan },
  ["@punctuation.delimiter"] = { fg = c.fg_bright },
  ["@punctuation.bracket"] = { fg = c.fg_bright },
  ["@comment"] = { fg = c.muted },
  ["@markup.heading"] = { fg = c.blue },
  ["@markup.strong"] = { fg = c.fg_bright },
  ["@markup.link"] = { fg = c.blue, underline = true },
  ["@markup.raw"] = { fg = c.green },

  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { underline = true, sp = c.red },
  DiagnosticUnderlineWarn = { underline = true, sp = c.yellow },
  DiagnosticUnderlineInfo = { underline = true, sp = c.blue },
  DiagnosticUnderlineHint = { underline = true, sp = c.cyan },
  DiagnosticVirtualTextError = { fg = c.red, bg = "#342529" },
  DiagnosticVirtualTextWarn = { fg = c.yellow, bg = "#332D22" },
  DiagnosticVirtualTextInfo = { fg = c.blue, bg = "#242C3D" },
  DiagnosticVirtualTextHint = { fg = c.cyan, bg = "#223037" },

  GitSignsAdd = { fg = c.green, bg = c.bg },
  GitSignsChange = { fg = c.blue, bg = c.bg },
  GitSignsDelete = { fg = c.red, bg = c.bg },
  IblIndent = { fg = c.subtle },
  IblScope = { fg = c.blue },
  MiniIndentscopeSymbol = { fg = c.blue },

  -- Telescope Suggestions (Optimized for maximum visibility & contrast)
  TelescopeNormal = { fg = "#FFFFFF", bg = c.bg_float },
  TelescopeBorder = { fg = c.blue, bg = c.bg_float },
  TelescopeTitle = { fg = c.blue, bg = c.bg_float, bold = true },
  TelescopePromptNormal = { fg = "#FFFFFF", bg = "#25282F" },
  TelescopePromptBorder = { fg = c.blue, bg = "#25282F" },
  TelescopePromptPrefix = { fg = c.yellow, bold = true },
  TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
  TelescopeSelection = { fg = "#FFFFFF", bg = "#3D4452", bold = true },
  TelescopeSelectionCaret = { fg = c.cyan, bg = "#3D4452", bold = true },
  TelescopeMatching = { fg = c.orange, bold = true, underline = true },
  TelescopeResultsNormal = { fg = "#FFFFFF", bg = c.bg_float },
  TelescopeResultsBorder = { fg = c.border, bg = c.bg_float },
  TelescopeResultsTitle = { fg = c.bg, bg = c.purple, bold = true },
  TelescopePreviewNormal = { fg = "#EFF2F6", bg = c.bg },
  TelescopePreviewBorder = { fg = c.border, bg = c.bg },
  TelescopePreviewTitle = { fg = c.bg, bg = c.green, bold = true },
  TelescopeMultiSelection = { fg = c.cyan, bold = true },
  TelescopeMultiIcon = { fg = c.cyan, bold = true },
  TelescopeResultsFile = { fg = "#FFFFFF", bold = true },
  TelescopeResultsFileIcon = { fg = c.blue },
  TelescopeResultsDirectory = { fg = c.blue, bold = true },
  TelescopeResultsPath = { fg = c.muted },
  TelescopeResultsLink = { fg = c.cyan },
  TelescopeResultsSpecialComment = { fg = c.muted },
  TelescopeResultsIdentifier = { fg = c.yellow },
  TelescopeResultsLineNr = { fg = c.muted },
  TelescopeResultsComment = { fg = "#B5C2D5" },
  TelescopeResultsClass = { fg = c.cyan },
  TelescopeResultsField = { fg = c.fg_bright },
  TelescopeResultsFunction = { fg = c.blue },
  TelescopeResultsMethod = { fg = c.blue },
  TelescopeResultsOperator = { fg = c.cyan },
  TelescopeResultsStruct = { fg = c.cyan },
  TelescopeResultsVariable = { fg = c.fg_bright },
  TelescopeResultsDiffAdd = { fg = c.green },
  TelescopeResultsDiffChange = { fg = c.blue },
  TelescopeResultsDiffDelete = { fg = c.red },

  BlinkCmpMenu = { fg = c.fg, bg = c.bg_float },
  BlinkCmpMenuBorder = { fg = c.border, bg = c.bg_float },
  BlinkCmpMenuSelection = { fg = c.fg_bright, bg = "#374258" },
  BlinkCmpDoc = { fg = c.fg, bg = c.bg_float },
  BlinkCmpDocBorder = { fg = c.border, bg = c.bg_float },
  BlinkCmpLabelMatch = { fg = c.yellow },
  BlinkCmpLabelDeprecated = { fg = c.muted, strikethrough = true },
  BlinkCmpKind = { fg = c.cyan },
  BlinkCmpSource = { fg = c.muted },

  NeoTreeNormal = { fg = c.fg, bg = c.bg },
  NeoTreeNormalNC = { fg = c.fg, bg = c.bg },
  NeoTreeDirectoryName = { fg = c.blue, bold = true },
  NeoTreeDirectoryIcon = { fg = c.blue },
  NeoTreeFileName = { fg = c.fg },
  NeoTreeFileIcon = { fg = c.blue },
  NeoTreeRootName = { fg = c.purple, bold = true },
  NeoTreeSymbolicLinkTarget = { fg = c.cyan },
  NeoTreeGitAdded = { fg = c.green },
  NeoTreeGitModified = { fg = c.blue },
  NeoTreeGitDeleted = { fg = c.red },
  NeoTreeIndentMarker = { fg = c.subtle },
  NeoTreeExpander = { fg = c.muted },
  NeoTreeWinSeparator = { fg = c.border, bg = c.bg },
  NeoTreeTitleBar = { fg = c.blue, bg = c.bg_float, bold = true },
  NeoTreeFloatTitle = { fg = c.blue, bg = c.bg_float, bold = true },
  NeoTreeFloatBorder = { fg = c.border, bg = c.bg_float },
  NeoTreeCursorLine = { bg = "#374258" },

  WhichKey = { fg = c.cyan, bold = true },
  WhichKeyKey = { fg = c.blue, bold = true },
  WhichKeyGroup = { fg = c.purple, bold = true },
  WhichKeyDesc = { fg = c.fg_bright },
  WhichKeyIcon = { fg = c.yellow },
  WhichKeySeparator = { fg = c.muted },
  WhichKeyNormal = { fg = c.fg, bg = c.bg_float },
  WhichKeyFloat = { fg = c.fg, bg = c.bg_float },
  WhichKeyBorder = { fg = c.blue, bg = c.bg_float },
  WhichKeyTitle = { fg = c.blue, bg = c.bg_float, bold = true },
  WhichKeyValue = { fg = c.muted },

  FlashLabel = { fg = c.bg, bg = c.yellow },
  FlashCurrent = { fg = c.bg, bg = c.orange },
  FlashMatch = { fg = c.fg_bright, bg = c.bg_active },

  SnacksNormal = { fg = c.fg, bg = c.bg },
  SnacksWinBar = { fg = c.fg, bg = c.bg },
  SnacksPickerNormal = { fg = c.fg, bg = c.bg_float },
  SnacksPickerBorder = { fg = c.border, bg = c.bg_float },
  SnacksPickerTitle = { fg = c.blue, bg = c.bg_float, bold = true },
  SnacksPickerKey = { fg = c.cyan, bold = true },
  SnacksPickerDesc = { fg = c.fg_bright },
  SnacksPickerFile = { fg = c.fg_bright },
  SnacksPickerDir = { fg = c.blue, bold = true },
  SnacksPickerPath = { fg = c.muted },
  SnacksPickerMatch = { fg = c.orange, bold = true },
  SnacksPickerSelected = { fg = c.fg_bright, bg = c.bg_active },
  SnacksPickerPrefix = { fg = c.yellow },
  SnacksPickerIcon = { fg = c.blue },
  SnacksPickerTree = { fg = c.subtle },
  SnacksPickerSearch = { fg = c.yellow },
  SnacksPickerInput = { fg = c.fg_bright, bg = c.bg_active },
  SnacksExplorerFile = { fg = c.fg_bright },
  SnacksExplorerDir = { fg = c.blue, bold = true },
}

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "prodev"

for group, settings in pairs(hl) do
  vim.api.nvim_set_hl(0, group, settings)
end

